
#define HAVE_VALGRIND 1

#define PVOID_SIZE 8
#define INT_SIZE 4

/* #undef ASYNCSCHEDULER_CONTEXTENGINE_WINFIBER */
#define ASYNCSCHEDULER_CONTEXTENGINE_UCONTEXT 1
/* #undef ASYNCSCHEDULER_CONTEXTENGINE_BOOSTCONTEXT */
