


scope s1
{
    struct s1 {}

    struct xx
    {
        s1 x;
        int8 y;


        variant xx
        {
            int8 x;
            int8 y;
        }
        
        iface myfBase : myf {}
        iface myfBase2 {}
        
        iface myf
            : ::s1::xx::myfBase, myfBase2
        {
            in void m1(xx p1, x p2);
            
            
            //include "inc.idl";
        }


    }
    

}

scope s1
{
    alias x=xx::myf;
}